# Generated by Django 5.0.6 on 2024-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=20)),
                ('teacher_id', models.SmallIntegerField()),
                ('date_of_joining', models.DateField()),
                ('nationality', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('years_of_experience', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
